[".config/zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "672h"

[".config/zsh/custom/plugins/zsh-256color"]
    type = "archive"
    url = "https://github.com/chrissicool/zsh-256color/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "672h"

[".config/zsh/custom/plugins/1-fzf-tab"]
    type = "git-repo"
    url = "https://github.com/Aloxaf/fzf-tab"
    refreshPeriod = "672h"

[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/blehrer/kickstart.nvim"
    refreshPeriod = "24h"
    [".config/nvim".pull]
        args = ["--ff-only"]

[".config/kitty/kitty-themes"]
    type = "git-repo"
    url = "https://github.com/dexpota/kitty-themes"
    [".config/kitty/kitty-themes".pull]
        args = ["--depth 1"]
