#!/usr/bin/env bash

function xit-down() {
    local pids=$(jps -l | grep xit.jar | awk '{print $1}')
    echo "Killing xit.jar(s) ($pids)"
    for pid in `echo $pids | sed -e 's/\n/ /g'`; do
        kill $pid
    done
}
xit-down
