#!/usr/bin/env zsh

source .env
readonly GITDIR=$(git rev-parse show-toplevel)

[ -f ~/.cache/xit/installation.err.log ] && rm ~/.cache/xit/installation.err.log
cd $XIT_INSTALL_DIR && ./shutdown.sh 
cd $GITDIR
./gradlew dist 
for x in $(ls $XIT_INSTALL_DIR | grep -v home); do rm -rfd $XIT_INSTALL_DIR/$x ; done
mkdir -p $XIT_INSTALL_DIR/home/packages
cp .env $XIT_INSTALL_DIR 
cp $XIT_SECRET_CONFIGURATION_PROPERTIES $XIT_INSTALL_DIR/home/configuration.properties 
cd $XIT_INSTALL_DIR 
jenv local 1.8 
cd $GITDIR 
./dist/install.sh dist/xit-12.0.0-SNAPSHOT.zip 2> ~/.cache/xit/installation.err.log 
[ -S ~/.cache/xit/installation.err.log ] && {
    echo ~/.cache/xit/installation.err.log 
    echo --------- 
    cat ~/.cache/xit/installation.err.log
} || rm ~/.cache/xit/installation.err.log
