# Application bindings
bindd = SUPER ALT, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new
# MEH   = CONTROL ALT SHIFT
# HYPER = CONTROL ALT SHIFT SUPER
bindd = CONTROL, apostrophe, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, semicolon, Terminal, exec, uwsm-app -- omarchy-launch-tui zsh -lic zellij-sesh
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, G, Signal, exec, omarchy-launch-or-focus ^signal$ "uwsm-app -- signal-desktop"
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, W, Typora, exec, uwsm-app -- typora --enable-wayland-ime
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
unbind = SUPER, W
bindd = SUPER, Q, Close window, killactive,

# Clamshell stuff
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, preferred, auto, 1.6"
bindl = , switch:off:Lid Switch, exec, notify-send "clamshell opened"
bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable"
bindl = , switch:on:Lid Switch, exec, notify-send "clamshell closed"
# Trigger kanshi or manual check on lid events
# bindl=,switch:on:Lid Switch,exec,$(hyprctl keyword monitor "eDP-1, disable && notify-send "clamshell closed")
# bindl=,switch:off:Lid Switch,exec,$(kanshictl reload && notify-send "clamshell opened")

# Bisecting mouse grid
binddc=CONTROL SHIFT, semicolon, Pointer grid, exec, ~/.config/hypr/killeval.sh wl-kbptr
binddc=CONTROL SHIFT, slash, Pointer hints, exec, ~/.config/hypr/killeval.sh hints

bindd = CONTROL ALT SHIFT, h, Move window left within workspace, swapwindow, l
bindd = CONTROL ALT SHIFT, l, Move window left within workspace, swapwindow, r

# Tiling
unbind = SUPER, j
bindd = ALT, SLASH, Toggle window split, togglesplit

# Zoom in
bind = CONTROL ALT SHIFT, PAGE_UP, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float + 0.1')
# Zoom out
bind = CONTROL ALT SHIFT, PAGE_DOWN, exec, hyprctl -q keyword cursor:zoom_factor $(hyprctl getoption cursor:zoom_factor -j | jq '.float - 0.1')
