[tools]
jq = "latest"
starship = "latest"
node = "latest"
usage = "latest"
ripgrep = "latest"
lazygit = "latest"
java = "21"
python = "3"
go = "latest"
deno = "latest"
pipx = "latest"

[settings]
experimental = true
