[tools]
jq = "latest"
starship = "latest"
neovim = "latest"
node = "latest"
usage = "latest"
ripgrep = "latest"
lazygit = "latest"
java = "latest"
python = "3"
go = "latest"

[settings]
experimental = true
