#!/usr/bin/env bash

alias @wh='cd $WHOME'
alias wh='@wh'
alias intellij=idea

function idea() {
  local version=`find ~/.cache/JetBrains/ -maxdepth 1 -mindepth 1 -type d | tail -n 1`
  local timestamp=`date +%Y-%m-%d-%H%M%z.%s`
  local logfile="$version/log/runtime/idea.$timestamp.log"
  echo logfile: $logfile
  dex $APPS/jetbrains-idea.desktop &> $logfile &
}
