#!/usr/bin/env bash
alias @cdw='cd $ONAIR'
alias @oas='cd $ONAIR'
alias @xit='cd $ONAIR/xit.git'
alias @x='cd $ONAIR/xit.git'
alias @xh='cd $XH'
alias @tll='cd $ONAIR/translator-linear.git'
alias @fwd='cd $ONAIR/translator-linear.git/fwd'
alias @ui='cd $ONAIR/fwd-ui'
alias @data='cd $ONAIR/data'
alias iamFwdNonprod="cyberpeacock_login --user $SSO --profile fwd --arn arn:aws:iam::615757282153:role/FWDTeam --duration 3600 && cpProfile fwd saml && aws eks update-kubeconfig --name fwd-eks-us-east-1 --profile fwd"
alias iamFwdProd="cyberpeacock_login --user $SSO --profile fwd-prod --arn arn:aws:iam::451289765098:role/FWDTeam --duration 3600 && cpProfile fwd-prod saml && aws eks update-kubeconfig --name fwd-eks-us-east-1 --profile fwd-prod"

